spring:
  application:
    version: 0.0.1

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/voucher?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234!

  sql:
    init:
      platform: mysql
      mode: always

path:
  csv: src/main/resources/file/customer_blackList.csv
  txt: src/main/resources/file/vouchers.txt
